services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Migrify\MigrationArtefact\PhpHtmlToSymfonyController\Rector\:
        resource: '../src'
        exclude:
            - '../src/ValueObject/*'
            - '../src/Rector/**/*Rector.php'
